#  Copyright ⓒ 2018-2019 ThePhD.
#
#  Distributed under the Boost Software License, Version 1.0. (See
#  accompanying file LICENSE or copy at
#  http://www.boost.org/LICENSE_1_0.txt)
#
#  See https://github.com/ThePhD/out_ptr/blob/master/docs/out_ptr.adoc for documentation.


max_jobs: 4

pull_requests:
  do_not_increment_build_number: true

image:
- Visual Studio 2015
- Visual Studio 2017

platform:
- x64
- x86

matrix:
  allow_failures:
    - image: Visual Studio 2015

install:
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive

before_build:
- md build-debug
- cd build-debug
- cmake .. -DCMAKE_BUILD_TYPE=Debug -DPHD_OUT_PTR_TESTS=ON -DPHD_OUT_PTR_EXAMPLES=ON 
- cd ..
- md build-release
- cd build-release
- cmake .. -DCMAKE_BUILD_TYPE=Release -DPHD_OUT_PTR_TESTS=ON -DPHD_OUT_PTR_EXAMPLES=ON 
- cd ..

build_script:
- cd build-debug
- cmake --build . --config Debug
- cd ..
- cd build-release
- cmake --build . --config Release
- cd ..

test_script:
- cd build-debug
- ctest --output-on-failure --build-config Debug
- cd ..
- cd build-release
- ctest --output-on-failure --build-config Release
- cd ..
